config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'pages/home'
  get 'pages/about'

  get 'dashboard' => 'dashboard#dashboard'

  resources :books
  get :xchange_send_email, to: 'books#xchange_send_email', as: :xchange_send_email

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
	has_attached_file :image, :styles => {:thumb => '100x100>', :square => '200x200#', :medium => '300x300>'}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(book)
     "/books"
  end

end

#configure devise
#conf.action_mailer.perform_deliveres=true

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :xchange]

  def index
    @book = Book.all
  end

  def show
    @user= current_user
    puts "#{@user.to_json}"
  end

  def new
    @book = Book.new
  end

  def edit

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update


    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy

    @book.destroy

    redirect_to books_path
  end

  def profile
    @book=current_user.books
  end

  def xchange_send_email
    @user= current_user
    UserMailer.notification_email(@book,@user).deliver
    redirect_to @book, notice: 'Email was successfully sent. Wait for an answer. '
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:name, :author, :descrption, :image)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    @book = current_user.books
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_books.html.erb
 <div class = container>
  <%= link_to 'Add book', new_book_path %>
  </br>
  </br>

  <div class="row">
    <% @book.each do |book| %>
    <div class="col-sm-2 col-md-2">
      <div class="thumbnail">
        <%= image_tag book.image.url(:medium) %>
        <div class="caption">
          <h4><%= book.name %></h4>
          <h5><%= book.author %></h5>
          <h5><%= book.user.name %></h5>
          <p><%= book.descrption %></p>
          <p>
          <%= link_to 'Show', book_path(book), class: "btn btn-primary", role: "button" %>
          <%= link_to 'Edit', edit_book_path(book), class: "btn btn-primary", role: "button" %>
          <%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: "are you sure?"}, class: "btn btn-primary", role: "button" %>
          <%= link_to 'Xchange', xchange_send_email_path, class: "btn btn-primary", role: "button" %>
          </p>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

<!--:controller => "books", :action => "xchange_send_email", :id => @book.id-->

app/views/books/_form.html.erb
<%= form_for @book, html: {multipart: true } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count,"error") %> prohibited this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Autor %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :Descripción %><br>
    <%= f.text_area :descrption %>
  </p>
  <p>
    <%= f.label :Imagen %><br>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Edit your book</h1>

<%= render 'form' %>
<%= link_to 'Your books', books_path %>

app/views/books/index.html.erb
<% if user_signed_in? %>
  <p class= "borde">Welcome <strong><%= current_user.name %></strong>. It's time to Xchange a Book.</p>
  <p>Books for Xchange</p>
<% end %>
<%= render 'books'%>

app/views/books/new.html.erb
<h1>Xchange a Book</h1>
<%= render 'form' %>
<%= link_to 'Your books', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Upload:</strong>
  <%= @book.updated_at.strftime("%Y-%m-%d") %>
</p>
<p>
  <strong>Nombre:</strong>
  <%= @book.name %>
</p>
<p>
  <strong>Autor:</strong>
  <%= @book.author %>
</p>
<p>
  <%= image_tag @book.image.url(:medium) %>
</p>
<p>
  <strong>Descripción:</strong>
  <%= @book.descrption %>
</p>



<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Your books', books_path %>

app/views/dashboard/dashboard.html.erb
<h2>Mis datos</h2>


<%= render 'books/books'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BXchange</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header brand">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll">
              <i class="fa fa-play-circle"></i>
              <ul style="font-size: 25px">
                <%= link_to 'BXchange',  root_path  %>
              </ul>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
              <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
              <li class="hidden">
                  <a href="#page-top"></a>
              </li>
              <!-- Esto es para hacer el SIGN UP y LOG IN-->
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Edit account', edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to "My Profile", dashboard_path %>
                </li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
              <li>
                <%= link_to 'About', pages_about_path %>
              </li>
              <li>
                  <a class="page-scroll" href="#contact">Contact</a>
              </li>
                <li>
                  <%= link_to "Sign up", new_user_registration_path %>
                </li>
                <li>
                  <%= link_to "Log in", new_user_session_path %>
                </li>
              <% end %>
              </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <% if notice %>

    <% end %>
    <% if alert %>

    <% end %>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us or our APP</h1>
<p>We make connections between two people who want to exchange their books. Welcome!</p>

app/views/pages/home.html.erb
<!-- Intro Header -->
<header class="intro">
	<div class="intro-body">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="brand-heading">Book Xchange</h1>
          <p class="intro-text" style="color: black">
          	<strong>It's time to exchange your books for new ones!
              <br>Sign up and start a new reading </strong>
          </p>
	        <li>
            <%= link_to "Sign up", new_user_registration_path %>
           </li>
        </div>
      </div>
    </div>
	</div>
</header>

app/views/send_notification/notification_email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset="utf-8' http-equiv='Content-Type' />
</head>
  <body>
    <h1>Hi <%= @book.user.name %></h1>
    <p>
      This emails is just a proof. I hope this work.
      El correo de <%= @user.name%> es <%= @user.email%>

    </p>
  </body>
</html>

app/views/send_notification/notification_email.text.erb
Hi <%= @user.name %>

This emails is just a proof. I hope this work.